---
# tasks file for ChangeMOTD
  - name: Change MOTD
    copy: 
      content: " \n"
      dest: /etc/motd

  - name: Disable MOTD
    file:
      dest: "/etc/update-motd.d"
      mode: "u-x,g-x,o-x"
      state: directory
      recurse: yes
